import { Song } from "./mockData";

export interface IshqMood {
  id: string;
  name: string;
  nameHindi: string;
  emoji: string;
  tagline: string;
  color: string;
  accent: string;
}

export interface IshqStation {
  id: string;
  name: string;
  nameHindi: string;
  emoji: string;
  description: string;
  songCount: number;
  badge: string;
  thumbnail: string;
}

export const ISHQ_QUOTES = [
  "Kuch gaane sune nahi jaate... mehsoos kiye jaate hain. ❤️",
  "Some memories have a soundtrack. ✨",
  "Naam nahi lenge... gaana samajh jayega. 🎧",
  "Kuch log gaane ban jaate hain. 🌙",
  "Har kisi ki ek playlist hoti hai, jo kisi ek insaan ke naam hoti hai. 💕",
  "2 AM + headphones + your favourite voice. 🌧️",
];

export const ISHQ_FM_SAYS = [
  "Aaj kisi ki yaad aa rahi hai kya? ❤️",
  "Ye gaana unke naam... jinko kabhi keh nahi paaye.",
  "Naam nahi lenge... bas dil tak baat pahunch jaye.",
  "Kuch log paas nahi hote, par unke gaane hamesha rehte hain.",
  "Late night thoughts ko ek sur mil gaya hai.",
];

export const ISHQ_MOODS: IshqMood[] = [
  {
    id: "in-love",
    name: "In Love",
    nameHindi: "दिल फुल है",
    emoji: "😍",
    tagline: "Dil full hai ❤️",
    color: "from-pink-500/30 to-rose-600/30",
    accent: "#FF4F8B",
  },
  {
    id: "missing",
    name: "Missing Someone",
    nameHindi: "याद आ रही है",
    emoji: "🥹",
    tagline: "Yaad aa rahi hai?",
    color: "from-purple-500/30 to-indigo-600/30",
    accent: "#8B5CF6",
  },
  {
    id: "heartbroken",
    name: "Heartbroken",
    nameHindi: "टूटा दिल",
    emoji: "💔",
    tagline: "Thoda dard bhi zaroori hai.",
    color: "from-blue-600/30 to-slate-800/40",
    accent: "#3B82F6",
  },
  {
    id: "late-night",
    name: "2 AM Zone",
    nameHindi: "रात के दो बजे",
    emoji: "🌙",
    tagline: "2 AM thoughts.",
    color: "from-indigo-900/40 to-purple-950/60",
    accent: "#A855F7",
  },
  {
    id: "crush",
    name: "Crush FM",
    nameHindi: "चोरी-चोरी",
    emoji: "🫶",
    tagline: "Naam nahi lenge.",
    color: "from-amber-400/20 to-pink-500/30",
    accent: "#F43F5E",
  },
  {
    id: "baarish",
    name: "Baarish Wala Ishq",
    nameHindi: "बारिश और तुम",
    emoji: "🌧️",
    tagline: "Rain + headphones.",
    color: "from-cyan-600/30 to-blue-700/30",
    accent: "#06B6D4",
  },
  {
    id: "one-sided",
    name: "One-Sided Love",
    nameHindi: "एकतरफा प्यार",
    emoji: "🥀",
    tagline: "Keh nahi paaye.",
    color: "from-red-900/30 to-violet-900/40",
    accent: "#E11D48",
  },
  {
    id: "happy-love",
    name: "Happy Love",
    nameHindi: "सुकून वाला प्यार",
    emoji: "✨",
    tagline: "Pyaar achha lag raha hai.",
    color: "from-emerald-500/20 to-teal-600/30",
    accent: "#10B981",
  },
];

export const ISHQ_STATIONS: IshqStation[] = [
  {
    id: "romantic-hits",
    name: "Romantic Hits",
    nameHindi: "सदाबहार रोमांटिक",
    emoji: "❤️",
    description: "The biggest Bollywood love anthems and evergreen melodies.",
    songCount: 150,
    badge: "Most Popular",
    thumbnail: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "arijit-special",
    name: "Arijit Special",
    nameHindi: "अरिजीत स्पेशल",
    emoji: "🎙️",
    description: "Soul-stirring romantic & emotional masterpieces by Arijit Singh.",
    songCount: 85,
    badge: "Top Artist",
    thumbnail: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "broken-hearts",
    name: "Broken Hearts",
    nameHindi: "दर्द-ए-दिल",
    emoji: "💔",
    description: "Raw heartbreak, separation, and songs for heavy hearts.",
    songCount: 90,
    badge: "Emotional",
    thumbnail: "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "late-night-ishq",
    name: "Late Night Ishq",
    nameHindi: "रात की खामोशी",
    emoji: "🌙",
    description: "Slow-paced acoustic, lofi romantic gems for 2 AM stargazing.",
    songCount: 110,
    badge: "2 AM Vibe",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "90s-love",
    name: "90s Love",
    nameHindi: "90s की मोहब्बत",
    emoji: "📻",
    description: "Golden era Bollywood romance: Kumar Sanu, Udit Narayan, Alka Yagnik.",
    songCount: 120,
    badge: "Evergreen",
    thumbnail: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "baarish-wala-ishq",
    name: "Baarish Wala Ishq",
    nameHindi: "भीगे लम्हे",
    emoji: "🌧️",
    description: "Raindrops on windows, cold coffee, and soothing melodies.",
    songCount: 65,
    badge: "Monsoon",
    thumbnail: "https://images.unsplash.com/photo-1519692933481-e162a57d6721?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "crush-fm",
    name: "Crush FM",
    nameHindi: "पहली नज़र का जादू",
    emoji: "🫶",
    description: "Butterflies, cute smiles, and youthful upbeat romantic tunes.",
    songCount: 75,
    badge: "Gen-Z",
    thumbnail: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "one-sided-love",
    name: "One-Sided Love",
    nameHindi: "अनकही बातें",
    emoji: "🥀",
    description: "Unexpressed feelings and beautiful memories kept in silence.",
    songCount: 80,
    badge: "Soulful",
    thumbnail: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
  },
];

export const ISHQ_FALLBACK_SONGS: Song[] = [
  {
    id: "ishq-1",
    title: "Apna Bana Le",
    artist: "Arijit Singh • Sachin-Jigar",
    thumbnail: "https://i.ytimg.com/vi/ElZfdU54Cp8/hqdefault.jpg",
    youtubeVideoId: "ElZfdU54Cp8",
    duration: "4:21",
    durationSeconds: 261,
    category: "Ishq FM",
    playCount: 198420,
    likeCount: 64200,
    addedAgo: "Dil Se",
    isLiked: false,
  },
  {
    id: "ishq-2",
    title: "Tum Hi Ho",
    artist: "Arijit Singh • Mithoon",
    thumbnail: "https://i.ytimg.com/vi/UMbM7QvP_V0/hqdefault.jpg",
    youtubeVideoId: "UMbM7QvP_V0",
    duration: "4:22",
    durationSeconds: 262,
    category: "Ishq FM",
    playCount: 184500,
    likeCount: 58200,
    addedAgo: "Dil Se",
    isLiked: false,
  },
  {
    id: "ishq-3",
    title: "Raataan Lambiyan",
    artist: "Jubin Nautiyal • Asees Kaur",
    thumbnail: "https://i.ytimg.com/vi/EDvL7pW9m_8/hqdefault.jpg",
    youtubeVideoId: "EDvL7pW9m_8",
    duration: "3:50",
    durationSeconds: 230,
    category: "Ishq FM",
    playCount: 162300,
    likeCount: 51200,
    addedAgo: "Dil Se",
    isLiked: false,
  },
  {
    id: "ishq-4",
    title: "Agar Tum Saath Ho",
    artist: "Alka Yagnik • Arijit Singh",
    thumbnail: "https://i.ytimg.com/vi/xRb8hUVWDAI/hqdefault.jpg",
    youtubeVideoId: "xRb8hUVWDAI",
    duration: "5:41",
    durationSeconds: 341,
    category: "Ishq FM",
    playCount: 189100,
    likeCount: 67300,
    addedAgo: "Dil Se",
    isLiked: false,
  },
  {
    id: "ishq-5",
    title: "Shayad",
    artist: "Arijit Singh • Pritam",
    thumbnail: "https://i.ytimg.com/vi/bC-m4H048_0/hqdefault.jpg",
    youtubeVideoId: "bC-m4H048_0",
    duration: "4:07",
    durationSeconds: 247,
    category: "Ishq FM",
    playCount: 145200,
    likeCount: 43200,
    addedAgo: "Dil Se",
    isLiked: false,
  },
  {
    id: "ishq-6",
    title: "Shayad",
    artist: "Arijit Singh • Pritam",
    thumbnail: "https://i.ytimg.com/vi/ILzIqjXfC3A/hqdefault.jpg",
    youtubeVideoId: "ILzIqjXfC3A",
    duration: "4:07",
    durationSeconds: 247,
    category: "Ishq FM",
    playCount: 138700,
    likeCount: 41200,
    addedAgo: "Dil Se",
    isLiked: false,
  },
  {
    id: "ishq-7",
    title: "Kaise Hua",
    artist: "Vishal Mishra",
    thumbnail: "https://i.ytimg.com/vi/4mN_3K2K9-Q/hqdefault.jpg",
    youtubeVideoId: "4mN_3K2K9-Q",
    duration: "3:54",
    durationSeconds: 234,
    category: "Ishq FM",
    playCount: 129000,
    likeCount: 38700,
    addedAgo: "Dil Se",
    isLiked: false,
  },
  {
    id: "ishq-8",
    title: "Pee Loon",
    artist: "Mohit Chauhan",
    thumbnail: "https://i.ytimg.com/vi/5y3y2-V32q4/hqdefault.jpg",
    youtubeVideoId: "5y3y2-V32q4",
    duration: "4:47",
    durationSeconds: 287,
    category: "Ishq FM",
    playCount: 118400,
    likeCount: 35100,
    addedAgo: "Dil Se",
    isLiked: false,
  },
  {
    id: "ishq-9",
    title: "Jeene Laga Hoon",
    artist: "Atif Aslam • Shreya Ghoshal",
    thumbnail: "https://i.ytimg.com/vi/zpZ_aKTSkP4/hqdefault.jpg",
    youtubeVideoId: "zpZ_aKTSkP4",
    duration: "3:58",
    durationSeconds: 238,
    category: "Ishq FM",
    playCount: 154200,
    likeCount: 49800,
    addedAgo: "Dil Se",
    isLiked: false,
  },
  {
    id: "ishq-10",
    title: "Labon Ko",
    artist: "KK • Pritam",
    thumbnail: "https://i.ytimg.com/vi/K79gN48Kx-M/hqdefault.jpg",
    youtubeVideoId: "K79gN48Kx-M",
    duration: "5:42",
    durationSeconds: 342,
    category: "Ishq FM",
    playCount: 112000,
    likeCount: 39400,
    addedAgo: "Dil Se",
    isLiked: false,
  }
];
